# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88637a6c3924a116ebfcacd9ccbd09df16ff4e22d6d910c8caf930035b53db66d3404b90210e60e2b1c7bbed2a97a271476476e474858a52aae8480398991f3

test:
  secret_key_base: fbafe88dfbe34e6c7610f70bfe03aec330a564787122fd9ae2d82e173d9f967cb9b51d9a3efd6c2bf0ffc94084620b371e92251517465de1e8f2aa62731ce63c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
